project './SNLogger.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNLogger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNLogger
  pod 'Logan', '~> 1.2.8'

end
